### PR TITLE
✨ - Support non-coroutine handler

### PR DESCRIPTION
**Pull request by isac322**
Fixes https://github.com/DataDog/dd-trace-py/pull/3240#issuecomment-1036312734

### CODE REVIEW

**Review by ysk24ok — COMMENTED** [review]
Thank you for your contribution.
I've made some nits comments.

Also, would it be possible to add test cases to check non-async RPC is traced?

**Comment by ysk24ok** [comment]
> Also, would it be possible to add test cases to check non-async RPC is traced?

@isac322 Just to confirm, are you already working on this or not? If not, I'm gonna work on it.

**Comment by isac322** [comment]
@ysk24ok Sorry for late reply. I'm trying to add tests but because I'm new in ddtrace-py it's hard. It would be good if you could work on it.

**Comment by ysk24ok** [comment]
Added tests in ad26ed7. Using `TracedRpcMethodHandler` led to change constants, like `grpc-aio-server` -> `grpc-server`, so I updated the implementation.

**Review by ysk24ok — APPROVED** [review]
LGTM

**Comment by isac322** [comment]
@ysk24ok 

I got this error after apply your commit. I think `_TracedAioRpcMethodHandler` should not have async methods if given rpc handler is not coroutine function.

```
2022-02-18 14:13:17,695 [1] [ERROR] Unexpected [SynchronousOnlyOperation] raised by servicer method []
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 646, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 745, in _handle_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 511, in _handle_unary_unary_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 368, in _finish_handler_with_unary_response
  File "/src/statssrv/grpc_aio/aio_server_interceptor.py", line 124, in unary_unary
    return await _wrap_unary_response(self.__wrapped__.unary_unary, request, context, span)
  File "/src/statssrv/grpc_aio/aio_server_interceptor.py", line 75, in _wrap_unary_response
    call = behavior(request_or_iterator, servicer_context)
  File "/src/stats/utils.py", line 304, in inner
    return func(self, request, context)
  File "/src/statssrv/server.py", line 69, in ListUnitCreatives
    res = views.list_unit_creative(**req)
  File "/src/stats/views.py", line 57, in wrapped
    return func(*args, **kwargs)
  File "/src/stats/views.py", line 79, in list_unit_creative
    return DjangoJobRepository.list_unit_creative(request)
  File "/src/stats/adapters/repos/job.py", line 958, in list_unit_creative
    results = utils.execute_query_with_hourly_cache(connection, django_models.UnitCreative, query.get_sql())
  File "/src/stats/utils.py", line 172, in execute_query_with_hourly_cache
    return cast(List[QUERY_RESULT], _execute_query_with_hourly_cache(query=query, params=params))
  File "/usr/local/lib/python3.8/site-packages/cacheops/query.py", line 131, in wrapper
    result = func(*args, **kwargs)
  File "/src/stats/utils.py", line 170, in _execute_query_with_hourly_cache
    return execute_query(conn=conn, query=query, params=params)
  File "/src/stats/utils.py", line 127, in execute_query
    with conn.cursor() as cursor:
  File "/usr/local/lib/python3.8/site-packages/ddtrace/contrib/trace_utils.py", line 162, in wrapper
    return func(mod, pin, wrapped, instance, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/ddtrace/contrib/django/patch.py", line 85, in cursor
    cursor = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
```

**Comment by ysk24ok** [comment]
@isac322 Could you give me a reproducible example as well as an error message?

**Pull request merged**
